# Generated by Django 5.0.6 on 2024-05-21 14:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newsletter',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='newsletter',
            name='is_created',
        ),
        migrations.RemoveField(
            model_name='newsletter',
            name='is_sent',
        ),
        migrations.AddField(
            model_name='newsletter',
            name='status',
            field=models.CharField(choices=[('created', 'создана'), ('launched', 'запущена'), ('finished', 'завершена')], default='created', max_length=100, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='newsletter',
            name='periodicity',
            field=models.CharField(choices=[('daily', 'ежедневно'), ('weekly', 'еженедельно'), ('monthly', 'ежемесячно')], default='daily', max_length=100, verbose_name='периодичность'),
        ),
        migrations.CreateModel(
            name='Attempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('at_date', models.DateTimeField(auto_now_add=True, verbose_name='дата и время последней попытки')),
                ('is_success', models.BooleanField(default=False, verbose_name='успешность попытки')),
                ('server_response', models.TextField(default=False, verbose_name='ответ сервера')),
                ('newsletter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='newsletter', to='mailing.newsletter')),
            ],
            options={
                'verbose_name': 'Попытка',
                'verbose_name_plural': 'Попытки',
            },
        ),
    ]
