# Generated by Django 5.0.6 on 2024-05-23 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0003_alter_newsletter_at_date_alter_newsletter_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newsletter',
            name='at_date',
        ),
        migrations.AddField(
            model_name='newsletter',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='дата и время окончанмя рассылки'),
        ),
        migrations.AddField(
            model_name='newsletter',
            name='start_date',
            field=models.DateTimeField(auto_now=True, verbose_name='дата и время начала рассылки'),
        ),
    ]
