# Generated by Django 5.0.6 on 2024-05-24 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0006_newsletter_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsletter',
            name='name',
            field=models.CharField(blank=True, default='Рассылка', max_length=100, null=True, verbose_name='название рассылки'),
        ),
        migrations.AlterField(
            model_name='newsletter',
            name='periodicity',
            field=models.CharField(choices=[('ежедневно', 'ежедневно'), ('еженедельно', 'еженедельно'), ('ежемесячно', 'ежемесячно')], default='ежедневно', max_length=100, verbose_name='периодичность'),
        ),
        migrations.AlterField(
            model_name='newsletter',
            name='status',
            field=models.CharField(choices=[('создана', 'создана'), ('запущена', 'запущена'), ('завершена', 'завершена')], default='создана', max_length=100, verbose_name='статус'),
        ),
    ]
