# Generated by Django 4.2.2 on 2024-06-20 15:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0010_message_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsletter',
            name='clients',
            field=models.ManyToManyField(blank=True, related_name='Клиенты', to='mailing.client'),
        ),
        migrations.AlterField(
            model_name='newsletter',
            name='message',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Сообщение', to='mailing.message'),
        ),
        migrations.AlterField(
            model_name='newsletter',
            name='periodicity',
            field=models.CharField(choices=[('Ежедневно', 'Ежедневно'), ('Еженедельно', 'Еженедельно'), ('Ежемесячно', 'Ежемесячно')], default='Ежедневно', max_length=100, verbose_name='периодичность'),
        ),
        migrations.AlterField(
            model_name='newsletter',
            name='status',
            field=models.CharField(choices=[('Создана', 'Создана'), ('Запущена', 'Запущена'), ('Завершена', 'Завершена')], default='Создана', max_length=100, verbose_name='статус'),
        ),
    ]
