# Generated by Django 4.2.2 on 2024-06-21 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0013_alter_newsletter_clients_alter_newsletter_message'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='newsletter',
            options={'permissions': [('can_disable_status', 'Can disable')], 'verbose_name': 'Рассылка', 'verbose_name_plural': 'Рассылки'},
        ),
    ]
