# Generated by Django 4.2.2 on 2024-06-24 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0014_alter_newsletter_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='newsletter',
            options={'permissions': [('can_disable_newsletter', 'Can disable newsletter')], 'verbose_name': 'Рассылка', 'verbose_name_plural': 'Рассылки'},
        ),
    ]
